### ISSUE TITLE
Compare accuracy on the natural questions dataset with and without RAG

### ISSUE THREAD

**Issue by neubig** [neulab/llments#3]
# TODO

- [x] Implement RAG distmod operator
- [x] Base implementation of embedding using Contriever
- [x] Base implementation of retrieval using FAISS
- [x] Create example comparing before and after distmod accuracy on the dataset

# Blocked by

- https://github.com/neulab/llments/issues/2
